Repository ithacaxyz/porto, pull requests merged in 2025-06, with the labels that each got.

#376 docs(rpc-server): `wallet_health` -> `health`
  apps/docs/pages/rpc-server/health.md
  apps/docs/vocs.config.tsx
Labels: documentation

#378 docs(sdk): add missing space in perms demo
  apps/docs/components/HomePage.tsx
Labels: bug

#410 feat: firefox android
  apps/dialog/.env.example
  apps/dialog/vite.config.ts
  apps/docs/pages/sdk/faq.mdx
  apps/playground/.env.example
  apps/playground/src/App.tsx
  apps/~internal/lib/UserAgent.ts
  src/viem/Key.ts
Labels: claude-review
